### ISSUE TITLE
API to limit set of values

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/burst#56]
Imagine you have

```java
enum LocationSource {
  GPS,
  GLONASS,
  NETWORK,
  OTHER
}
```

And a test that should verify that behavior for `GPS` and `GLONASS` is the same:

```java
@Test
@Only({GPS, GLONASS})
public void processHighAccuracyLocationSource(LocationSource locationSource) {
  // assert/verify something.
}
```
Same can be applied to constructor/field injection.

Needed this several times this week. Do you think such thing fits into the library?

**Comment by artem-zinnatullin** [comment]
Technical problem here is that there is no `enum` type in java to reference all available enums like 

```java
@interface Only {
  enum[] value();
}
```

But, there is a possible solution with annotation for annotation:

```java
// User can create it for tests.
@BurstOnly // Marker that says to Burst that it's "limiter" annotation.
@interface Only { // Name does not matter.
  LocationSource[] value();
}
```

**Comment by JakeWharton** [comment]
Just use assumptions to filter?

**Comment by artem-zinnatullin** [comment]
ok, thanks. 

// Will probably build a JUnit rule for that then to not mix test code with filtering input from Burst.
