### ISSUE TITLE
Burst with Robolectric?

### ISSUE THREAD

**Issue by Kisty** [square/burst#59]
Is it possible to get burst working with Robolectric? I realise that adding two test runners would fail but have seen [here](https://github.com/robolectric/robolectric/wiki/Using-PowerMock) that if one can be a rule, then both should be OK to run together.

I've looked for a TestRule for Robolectric but can't find one and looked for one in this project but same problem. Any idea how to get them both working or how to write a rule for one or the other?

Cheers!

**Comment by JakeWharton** [comment]
There is currently no way. #32 was an attempt but it never was completed.

**Comment by JakeWharton** [comment]
No plans. We are ceasing development in favor of [TestParameterInjector](https://github.com/google/TestParameterInjector).
