### ISSUE TITLE
Burst annotation doesn't work

### ISSUE THREAD

**Issue by KurganovID** [square/burst#63]
I implemented libraries in Gradle file:
    testImplementation('com.squareup.burst:burst-junit4:1.2.0')
    testImplementation('com.squareup.burst:burst:1.2.0')
And receive next error when I run tests:
> Task :app:kaptDebugAndroidTestKotlin FAILED
e: C:\Work\LT_projects\Sephora_android\app\src\androidTest\java\com\ltst\app\ui\screen\start\DeeplinkTest.java:16: error: cannot find symbol
@RunWith(BurstJUnit4.class)
         ^

**Comment by Kisty** [comment]
Try `androidTestImplementation` instead of `testImplementation` in your `build.gradle` file.

**Comment by JakeWharton** [comment]
Indeed. Dependencies for `androidTest/` go in the `androidTestImplementation` configuration.

**Comment by KurganovID** [comment]
Thank's!
